version: "3.8"

services:
  backend:
    build:
      context: ./backend
    environment:
      - NODE_ENV=production
      - PORT=3333
      - JWT_SECRET=secret
      - DATABASE_URL=postgres://docker:docker@db:5432/project-manager
    ports:
      - "3333:3333"
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    environment:
      - VITE_API_URL=http://backend:3333
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/usr/src/app
    depends_on:
      - backend

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
